// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptMarketPlace.Data;

#nullable disable

namespace PromptMarketPlace.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614074454_AddOpenPromptFields")]
    partial class AddOpenPromptFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AdminAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AiApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiModelId")
                        .HasColumnType("int");

                    b.Property<double>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("float(3)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorProfileId")
                        .HasColumnType("int");

                    b.Property<int>("CreditCost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ExecutionCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPromptPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPromptPublicRequested")
                        .HasColumnType("bit");

                    b.Property<int>("OutputType")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SystemContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AiModelId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorProfileId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AiProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CostPer1KTokens")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("CostPerImage")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("CostPerSecondVideo")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AiProviderId");

                    b.ToTable("AiModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiProviderId = 1,
                            Capabilities = "[\"TextGeneration\",\"CodeGeneration\"]",
                            CostPer1KTokens = 0.003m,
                            IsActive = true,
                            IsDefault = true,
                            MaxTokens = 200000,
                            ModelId = "anthropic/claude-sonnet-4-6",
                            Name = "Claude Sonnet 4.6",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            AiProviderId = 1,
                            Capabilities = "[\"TextGeneration\",\"CodeGeneration\"]",
                            CostPer1KTokens = 0.00025m,
                            IsActive = true,
                            IsDefault = false,
                            MaxTokens = 200000,
                            ModelId = "anthropic/claude-haiku-4-5",
                            Name = "Claude Haiku 4.5",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            AiProviderId = 1,
                            Capabilities = "[\"TextGeneration\",\"CodeGeneration\"]",
                            CostPer1KTokens = 0.005m,
                            IsActive = true,
                            IsDefault = false,
                            MaxTokens = 128000,
                            ModelId = "openai/gpt-4o",
                            Name = "GPT-4o",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            AiProviderId = 1,
                            Capabilities = "[\"TextGeneration\",\"CodeGeneration\"]",
                            CostPer1KTokens = 0.00015m,
                            IsActive = true,
                            IsDefault = false,
                            MaxTokens = 128000,
                            ModelId = "openai/gpt-4o-mini",
                            Name = "GPT-4o Mini",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            AiProviderId = 1,
                            Capabilities = "[\"TextGeneration\",\"CodeGeneration\"]",
                            CostPer1KTokens = 0.00125m,
                            IsActive = true,
                            IsDefault = false,
                            MaxTokens = 1000000,
                            ModelId = "google/gemini-2.5-pro",
                            Name = "Gemini 2.5 Pro",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            AiProviderId = 1,
                            Capabilities = "[\"ImageGeneration\"]",
                            CostPerImage = 0.04m,
                            IsActive = true,
                            IsDefault = true,
                            ModelId = "black-forest-labs/flux-1.1-pro",
                            Name = "FLUX 1.1 Pro",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 7,
                            AiProviderId = 1,
                            Capabilities = "[\"ImageGeneration\"]",
                            CostPerImage = 0.003m,
                            IsActive = true,
                            IsDefault = false,
                            ModelId = "black-forest-labs/flux-schnell",
                            Name = "FLUX Schnell",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 8,
                            AiProviderId = 1,
                            Capabilities = "[\"ImageGeneration\"]",
                            CostPerImage = 0.035m,
                            IsActive = true,
                            IsDefault = false,
                            ModelId = "stabilityai/stable-diffusion-3-5",
                            Name = "Stable Diffusion 3.5",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 9,
                            AiProviderId = 1,
                            Capabilities = "[\"ImageGeneration\"]",
                            CostPerImage = 0.04m,
                            IsActive = true,
                            IsDefault = false,
                            ModelId = "openai/dall-e-3",
                            Name = "DALL-E 3",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 10,
                            AiProviderId = 1,
                            Capabilities = "[\"VideoGeneration\"]",
                            CostPerSecondVideo = 0.14m,
                            IsActive = true,
                            IsDefault = true,
                            ModelId = "kling/kling-1-6-pro",
                            Name = "Kling 1.6 Pro",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 11,
                            AiProviderId = 1,
                            Capabilities = "[\"VideoGeneration\"]",
                            CostPerSecondVideo = 0.05m,
                            IsActive = true,
                            IsDefault = false,
                            ModelId = "runway/gen-4",
                            Name = "Runway Gen-4",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = 12,
                            AiProviderId = 1,
                            Capabilities = "[\"VideoGeneration\"]",
                            CostPerSecondVideo = 0.003m,
                            IsActive = true,
                            IsDefault = false,
                            ModelId = "luma/dream-machine",
                            Name = "Luma Dream Machine",
                            SortOrder = 22
                        });
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AiProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKeyEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BalanceCurrency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BalanceJsonPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BalanceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActiveForAudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActiveForImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActiveForText")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActiveForVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProviderType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AiProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://openrouter.ai/api/v1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "گیت‌وی یکپارچه برای دسترسی به همه مدل‌های هوش مصنوعی",
                            IsActive = true,
                            IsActiveForAudio = false,
                            IsActiveForImage = false,
                            IsActiveForText = false,
                            IsActiveForVideo = false,
                            Name = "OpenRouter",
                            ProviderType = 0
                        });
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconClass = "fas fa-pen-nib",
                            Name = "تولید محتوا",
                            Slug = "content-creation",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IconClass = "fas fa-bullhorn",
                            Name = "مارکتینگ و تبلیغات",
                            Slug = "marketing",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IconClass = "fas fa-image",
                            Name = "تصویر و گرافیک",
                            Slug = "image-graphics",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IconClass = "fas fa-video",
                            Name = "ویدیو",
                            Slug = "video",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IconClass = "fas fa-code",
                            Name = "برنامه‌نویسی",
                            Slug = "programming",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            IconClass = "fas fa-gavel",
                            Name = "حقوقی و قراردادها",
                            Slug = "legal",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            IconClass = "fas fa-briefcase",
                            Name = "کسب‌وکار و مالی",
                            Slug = "business",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            IconClass = "fas fa-graduation-cap",
                            Name = "آموزش",
                            Slug = "education",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppExecution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ActualApiCost")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditUsed")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("OutputAudioUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputFormSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutputType")
                        .HasColumnType("int");

                    b.Property<string>("OutputVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppInputField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("AppInputFields");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppShowcaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutputText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutputType")
                        .HasColumnType("int");

                    b.Property<string>("OutputUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("ShowcaseItems");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("AppTags");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.CreatorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsFoundingCreator")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CreatorProfiles");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.CreditPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBestValue")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceRial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CreditPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreditAmount = 50,
                            IsActive = true,
                            IsBestValue = false,
                            Name = "بسته آزمایشی",
                            PriceRial = 250000m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreditAmount = 150,
                            IsActive = true,
                            IsBestValue = false,
                            Name = "بسته استارتر",
                            PriceRial = 600000m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreditAmount = 400,
                            IsActive = true,
                            IsBestValue = true,
                            Name = "بسته حرفه‌ای",
                            PriceRial = 1400000m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreditAmount = 1000,
                            IsActive = true,
                            IsBestValue = false,
                            Name = "بسته سازمانی",
                            PriceRial = 3000000m,
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.ErrorLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AiAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AiAnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.ExecutionInputValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ExecutionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("ExecutionInputValues");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.MessageThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("CreatorProfileId");

                    b.ToTable("MessageThreads");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditAmount")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZarinpalAuthority")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZarinpalRefId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.HasIndex("ZarinpalAuthority");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "شناسه پذیرنده زرین‌پال",
                            Group = "ZarinPal",
                            IsEncrypted = true,
                            Key = "ZarinPal:MerchantId",
                            Value = ""
                        },
                        new
                        {
                            Id = 2,
                            Description = "حالت تست (true) یا production (false)",
                            Group = "ZarinPal",
                            IsEncrypted = false,
                            Key = "ZarinPal:IsSandbox",
                            Value = "true"
                        },
                        new
                        {
                            Id = 3,
                            Description = "نام سایت",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "General:SiteName",
                            Value = "پرامپت مارکت"
                        },
                        new
                        {
                            Id = 4,
                            Description = "ایمیل پشتیبانی",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "General:SupportEmail",
                            Value = ""
                        },
                        new
                        {
                            Id = 5,
                            Description = "درصد کمیسیون پلتفرم",
                            Group = "Commission",
                            IsEncrypted = false,
                            Key = "Commission:PlatformPercent",
                            Value = "30"
                        },
                        new
                        {
                            Id = 6,
                            Description = "درصد کمیسیون سازندگان بنیان‌گذار",
                            Group = "Commission",
                            IsEncrypted = false,
                            Key = "Commission:FoundingCreatorPercent",
                            Value = "15"
                        },
                        new
                        {
                            Id = 7,
                            Description = "حداقل مبلغ برداشت (ریال)",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "Withdrawal:MinimumAmount",
                            Value = "500000"
                        },
                        new
                        {
                            Id = 8,
                            Description = "تایید خودکار سازندگان جدید",
                            Group = "General",
                            IsEncrypted = false,
                            Key = "Registration:AutoApproveCreator",
                            Value = "true"
                        });
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.ThreadMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFromAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThreadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("ThreadMessages");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.UserWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditBalance")
                        .HasColumnType("int");

                    b.Property<decimal>("EarningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEarned")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWithdrawn")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.WalletTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreditAmount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MoneyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.WithdrawalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankAccountInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorProfileId");

                    b.ToTable("WithdrawalRequests");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AdminAuditLog", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AiApp", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AiModel", "AiModel")
                        .WithMany("Apps")
                        .HasForeignKey("AiModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromptMarketPlace.Models.Domain.AppCategory", "Category")
                        .WithMany("Apps")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromptMarketPlace.Models.Domain.CreatorProfile", "Creator")
                        .WithMany("Apps")
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiModel");

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AiModel", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AiProvider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("AiProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppExecution", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AiApp", "App")
                        .WithMany("Executions")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", "User")
                        .WithMany("Executions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppInputField", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AiApp", "App")
                        .WithMany("InputFields")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppReview", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AiApp", "App")
                        .WithMany("Reviews")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppShowcaseItem", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AiApp", "App")
                        .WithMany("ShowcaseItems")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppTag", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AiApp", "App")
                        .WithMany("Tags")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.CreatorProfile", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", "User")
                        .WithOne("CreatorProfile")
                        .HasForeignKey("PromptMarketPlace.Models.Domain.CreatorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.ExecutionInputValue", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AppExecution", "Execution")
                        .WithMany("InputValues")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.MessageThread", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AiApp", "App")
                        .WithMany()
                        .HasForeignKey("AppId");

                    b.HasOne("PromptMarketPlace.Models.Domain.CreatorProfile", "Creator")
                        .WithMany("MessageThreads")
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.Payment", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.CreditPackage", "Package")
                        .WithMany("Payments")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.ThreadMessage", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.MessageThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.UserFavorite", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.AiApp", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.UserWallet", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("PromptMarketPlace.Models.Domain.UserWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.WalletTransaction", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.ApplicationUser", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.WithdrawalRequest", b =>
                {
                    b.HasOne("PromptMarketPlace.Models.Domain.CreatorProfile", "Creator")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("CreatorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AiApp", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("InputFields");

                    b.Navigation("Reviews");

                    b.Navigation("ShowcaseItems");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AiModel", b =>
                {
                    b.Navigation("Apps");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AiProvider", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppCategory", b =>
                {
                    b.Navigation("Apps");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.AppExecution", b =>
                {
                    b.Navigation("InputValues");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.ApplicationUser", b =>
                {
                    b.Navigation("CreatorProfile");

                    b.Navigation("Executions");

                    b.Navigation("Transactions");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.CreatorProfile", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("MessageThreads");

                    b.Navigation("WithdrawalRequests");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.CreditPackage", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PromptMarketPlace.Models.Domain.MessageThread", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
